config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3skim:
      branch: main
      repo: https://git.scc.kit.edu/synergy.o3as/o3skim
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-chartreuse-tetra.sh
        container: qc.acc_lumpy-carmine-uguisu
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ecru-labradoodle.sh
        container: qc.doc_paltry-buff-collie
      git.scc.kit.edu/synergy.o3as/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-dandelion-labradoodle.sh
        container: qc.doc_muzzy-sepia-ant
      git.scc.kit.edu/synergy.o3as/o3skim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-bistre-catfish.sh
        container: qc.doc_gamy-aquamarine-bison
      git.scc.kit.edu/synergy.o3as/o3skim restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-alizarin-chinook.sh
        container: qc.doc_hasty-green-tzu
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-heliotrope-sheepdog.sh
        container: qc.lic_skinny-zucchini-bordeaux
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cream-bandicoot.sh
        container: qc.met_baggy-brown-rat
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pear-wombat.sh
        container: qc.sec_squeaky-smalt-mandrill
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-puce-hound.sh
        container: qc.sty_skimpy-plum-macaw
      git.scc.kit.edu/synergy.o3as/o3skim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ivory-otter.sh
        container: qc.sty_shaky-magenta-dingo
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3skim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-black-lionfish.sh
        container: qc.ver_blurry-mustard-russel
timeout: 1800
