config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3skim:
      branch: main
      repo: https://github.com/EOSC-synergy/o3skim
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-apricot-lynx.sh
        container: qc.acc_sleazy-chartreuse-lionfish
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3skim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cinnamon-toad.sh
        container: qc.doc_homely-amethyst-wrasse
      github.com/EOSC-synergy/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-bistre-tetra.sh
        container: qc.doc_frumpy-orchid-quail
      github.com/EOSC-synergy/o3skim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cerulean-mastiff.sh
        container: qc.doc_muzzy-platinum-binturong
      github.com/EOSC-synergy/o3skim restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-scarlet-paradise.sh
        container: qc.doc_lovely-ruby-squid
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3skim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-buff-beaver.sh
        container: qc.lic_surly-seashell-vole
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3skim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-jade-chinchilla.sh
        container: qc.met_pasty-sapphire-rat
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3skim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-sangria-albatross.sh
        container: qc.sec_geeky-puce-forest
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3skim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-gold-monster.sh
        container: qc.sty_boozy-plum-horse
      github.com/EOSC-synergy/o3skim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-purple-vole.sh
        container: qc.sty_muggy-olive-avocet
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3skim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-coral-chinook.sh
        container: qc.ver_nippy-magnolia-woodlouse
timeout: 1800
