config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3skim:
      branch: main
      repo: https://github.com/EOSC-synergy/o3skim
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-azure-lemur.sh
        container: qc.acc_lovely-brown-gopher
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3skim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-scarlet-echidna.sh
        container: qc.doc_frumpy-cyan-tarantula
      github.com/EOSC-synergy/o3skim git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-alizarin-coral.sh
        container: qc.doc_nerdy-olive-akita
      github.com/EOSC-synergy/o3skim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-flax-kingfisher.sh
        container: qc.doc_wheezy-gold-eleuth
      github.com/EOSC-synergy/o3skim restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-zucchini-albatross.sh
        container: qc.doc_hilly-copper-shrimp
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3skim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-smalt-woodpecker.sh
        container: qc.lic_frumpy-pink-ibis
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3skim validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-corn-quoll.sh
        container: qc.met_stealthy-tangerine-snake
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3skim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cyan-gar.sh
        container: qc.sec_stinky-lilac-dragon
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3skim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lime-cockroach.sh
        container: qc.sty_blurry-firebrick-fowl
      github.com/EOSC-synergy/o3skim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cyan-lion.sh
        container: qc.sty_snoopy-bronze-tortoise
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3skim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-wheat-cichlid.sh
        container: qc.ver_scaly-peach-flounder
timeout: 1800
